### ISSUE TITLE
Passing a relative path

### ISSUE THREAD

**Issue by Ichunjo** [begna112/bvsfunc#3]
It would be very nice because I guess I'm not the only one, first, create the script on my PC, and second, push the script to a server.

So this:
```py
path = r'BDMV\STREAM\00001.m2ts'
ap.VideoSource(infile=path, trimlist="[None,-48]")
``` 

Instead of:
```py
path = r'F:\MY\FULL\PATH\BDMV\STREAM\00001.m2ts'
ap.VideoSource(infile=path, trimlist="[None,-48]")
```

**Comment by begna112** [comment]
Added in https://github.com/begna112/bvsfunc/commit/ffadbf97c168b24bdb5d15d1450319558c53bd94
